version: '3.8'

services:
  pinterest-downloader:
    image: pinterest-downloader
    ports:
      - 7861:7861
    environment:
      - PROXY_URL=http://192.168.31.85:10811
      - ZIP_DIR=/asset/zip
      - TASK_DIR=/asset/task
    volumes:
      - D:/Service/docker-volumes/pinterest/task:/asset/task
      - D:/Service/docker-volumes/pinterest/zip:/asset/zip
    command: python main.py --port 7861